In [5]:
import numpy as np
import scipy 
import pprint
from scipy import linalg
from sympy import *
import Matrix as CLO2


In [6]:
coeffequation1 = [8,1,1,5]
coeffequation2 = [1,8,1,5]
coeffequation3 = [1,1,8,5]

test = CLO2.matrix(coeffequation1,coeffequation2,coeffequation3)
test.gaussjordan()

Gauss Jordan Elimination
U DECOMPOSITION
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Step 1: -Row1 * 0.125 + Row2
Step 2: -Row1 * 0.125 + Row3 yielding: 

[[8 1 1 5]
 [0.0 7.87500000000000 0.875000000000000 4.37500000000000]
 [0.0 0.875000000000000 7.87500000000000 4.37500000000000]] 

Step3: -Row2 * 0.111111111111111 + Row 3 

[[8 1 1 5]
 [0.0 7.87500000000000 0.875000000000000 4.37500000000000]
 [0 0 7.77777777777778 3.88888888888889]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

And the roots are:


FiniteSet((1/2, 1/2, 1/2))

In [3]:
test.matrixA

Matrix([
[  7.0,    17.5,    50.75],
[ 17.5,   50.75,  161.875],
[50.75, 161.875, 548.1875]])

In [4]:
test.step1

Matrix([
[7.0, 17.5,  50.75,    1.1417],
[0.0,  7.0,   35.0,  -0.76635],
[0.0, 35.0, 180.25, -3.664125]])

In [5]:

test.step2

Matrix([
[7.0, 17.5, 50.75,            1.1417],
[0.0,  7.0,  35.0,          -0.76635],
[  0,    0,  5.25, 0.167625000000001]])

In [6]:
test.gaussjordan()

Gauss Jordan Elimination
U DECOMPOSITION
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Step 1: -Row1 * 2.5 + Row2
Step 2: -Row1 * 7.25 + Row3 yielding: 

[[7.00000000000000 17.5000000000000 50.7500000000000 1.14170000000000]
 [0.0 7.00000000000000 35.0000000000000 -0.766350000000000]
 [0.0 35.0000000000000 180.250000000000 -3.66412500000000]] 

Step3: -Row2 * 5.00000000000000 + Row 3 

[[7.00000000000000 17.5000000000000 50.7500000000000 1.14170000000000]
 [0.0 7.00000000000000 35.0000000000000 -0.766350000000000]
 [0 0 5.25000000000000 0.167625000000001]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

And the roots are:


FiniteSet((0.604421428571428, -0.269121428571429, 0.0319285714285714))