In [1]:
import numpy as np
import scipy 
import pprint
from scipy import linalg
from sympy import *
import Matrix as CLO2


In [2]:
coeffequation1 = [ 3, -0.1, -0.2, 7.85]
coeffequation2 = [ 0.1,  7,  -0.3, -19.3]
coeffequation3 = [ 0.3,  -0.2,  10, 71.4]

test = CLO2.matrix(coeffequation1,coeffequation2,coeffequation3)
test.gaussjordan()

Gauss Jordan Elimination
U DECOMPOSITION
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Step 1: -Row1 * 0.03333333333333333 + Row2
Step 2: -Row1 * 0.09999999999999999 + Row2 yielding: 

[[3.00000000000000 -0.100000000000000 -0.200000000000000 7.85000000000000]
 [0.0 7.00333333333333 -0.293333333333333 -19.5616666666667]
 [0.0 -0.190000000000000 10.0200000000000 70.6150000000000]] 

Step3: -Row2 * -0.0271299381247025 + Row 3 

[[3.00000000000000 -0.100000000000000 -0.200000000000000 7.85000000000000]
 [0.0 7.00333333333333 -0.293333333333333 -19.5616666666667]
 [0 0 10.0120418848168 70.0842931937173]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

And the roots are:


FiniteSet((3.0, -2.5, 7.0))

In [3]:
test.matrixA

Matrix([
[3.0, -0.1, -0.2],
[0.1,  7.0, -0.3],
[0.3, -0.2, 10.0]])

In [4]:
test.step1

Matrix([
[3.0,             -0.1,               -0.2,              7.85],
[0.0, 7.00333333333333, -0.293333333333333, -19.5616666666667],
[0.0,            -0.19,              10.02,            70.615]])

In [5]:

test.step2

Matrix([
[3.0,             -0.1,               -0.2,              7.85],
[0.0, 7.00333333333333, -0.293333333333333, -19.5616666666667],
[  0,                0,   10.0120418848168,  70.0842931937173]])

In [6]:
test.gaussjordan()

Gauss Jordan Elimination
U DECOMPOSITION
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Step 1: -Row1 * 0.03333333333333333 + Row2
Step 2: -Row1 * 0.09999999999999999 + Row2 yielding: 

[[3.00000000000000 -0.100000000000000 -0.200000000000000 7.85000000000000]
 [0.0 7.00333333333333 -0.293333333333333 -19.5616666666667]
 [0.0 -0.190000000000000 10.0200000000000 70.6150000000000]] 

Step3: -Row2 * -0.0271299381247025 + Row 3 

[[3.00000000000000 -0.100000000000000 -0.200000000000000 7.85000000000000]
 [0.0 7.00333333333333 -0.293333333333333 -19.5616666666667]
 [0 0 10.0120418848168 70.0842931937173]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

And the roots are:


FiniteSet((3.0, -2.5, 7.0))