In [1]:
import numpy as np
import scipy 
import pprint
from scipy import linalg
from sympy import *
import Matrix as CLO2


In [2]:
coeffequation1 = [2,1,1]
coeffequation2 = [2, 4, 5, 2 ]
coeffequation3 = [39, 43, 45, 74]


test = CLO2.matrix(coeffequation1,coeffequation2,coeffequation3)
test.gaussjordan()

Gauss Jordan Elimination
Step 1: Row1 * [2/5] - Row2
Step 2: Row1 * [39/5] - Row2 yielding: 

[[5 5 2 12]
 [0 2 21/5 -14/5]
 [0 4 147/5 -98/5]] 

Step3: Row2 * [2] - Row 3 

[[5 5 2 12]
 [0 2 21/5 -14/5]
 [0 0 21 -14]]

And the roots are:


{(8/3, 0, -2/3)}

In [3]:
test.matrixA

Matrix([
[ 5,  5,  2],
[ 2,  4,  5],
[39, 43, 45]])

In [4]:
test.step1

Matrix([
[5, 5,     2,    12],
[0, 2,  21/5, -14/5],
[0, 4, 147/5, -98/5]])

In [5]:
test.step2

Matrix([
[5, 5,    2,    12],
[0, 2, 21/5, -14/5],
[0, 0,   21,   -14]])

In [6]:
test.gaussjordan()

Gauss Jordan Elimination
Step 1: Row1 * [2/5] - Row2
Step 2: Row1 * [39/5] - Row2 yielding: 

[[5 5 2 12]
 [0 2 21/5 -14/5]
 [0 4 147/5 -98/5]] 

Step3: Row2 * [2] - Row 3 

[[5 5 2 12]
 [0 2 21/5 -14/5]
 [0 0 21 -14]]

And the roots are:


{(8/3, 0, -2/3)}