In [2]:
import numpy as np
import scipy 
import pprint
from scipy import linalg
from sympy import *
import Matrix as CLO2



In [23]:
coeffequation1 = [2,1,1, 3]
coeffequation2 = [1,-1,-1,24 ]
coeffequation3 = [1,2,1, 123]

np.set_printoptions(precision=3)

test = CLO2.matrix(coeffequation1,coeffequation2,coeffequation3)
print(test.matrixa)
test.matrixa = test.matrixa[1] -1


[[2 1 1]
 [1 -1 -1]
 [1 2 1]]


array([0, -2, -2], dtype=object)

Using Matrix Decomposition to calculate Roots

In [19]:
matrixa1 = test.matrixa[1] - test.matrixa[1][0]/test.matrixa[0][0]*test.matrixa[0]
matrixa1

array([0, -3/2, -3/2], dtype=object)

In [4]:
matrixu, l1,l2,l3 = test.uDecompost(test.matrixA)
matrixu

U DECOMPOSITION
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


TypeError: unsupported operand type(s) for /: 'One' and 'MutableDenseMatrix'

In [5]:
matrixl = test.lDecompost(l1,l2,l3)
matrixl

Matrix([
[1.0,  0.0, 0.0],
[0.5,  1.0, 0.0],
[0.5, -1.0, 1.0]])

In [7]:
matrixd = linalg.solve(np.array(matrixl.tolist()).astype(np.float64), test.matrixb)
matrixD = Matrix(matrixd)
matrixD

Matrix([
[ 3.0],
[-1.5],
[-3.0]])

In [8]:
ans= linalg.solve(np.array(matrixu.tolist()).astype(np.float64), matrixd)
Matrix(ans)

Matrix([
[ 1.0],
[-2.0],
[ 3.0]])

In [9]:
x1,x2 ,x3 = symbols('x1, x2, x3')
linsolve(Matrix(test.matrixdata), (x1,x2,x3))

{(1, -2, 3)}

$ \textbf{Using LU Decomposition to determine Inverse} $

using the principle of LU Decomposition
 $$ [A]^{-1} = \left[\{x\}_1 \{x\}_2 \{x\}_3 \right]$$
 
 where $ \{x\}_n $ represents the nth column of $[A]^{-1}$

In [36]:
test.matrixA

Matrix([
[6.0, 2.0, 1.0],
[2.0, 8.0, 3.0],
[1.0, 1.0, 5.0]])

In [37]:
matrixu, l1,l2,l3 = test.uDecompost(test.matrixA)
matrixu

Step 1: -Row1 * [0.333333333333333] + Row2
Step 2: -Row1 * [0.166666666666667] + Row2 yielding: 

[[6.00000000000000 2.00000000000000 1.00000000000000]
 [0 7.33333333333333 2.66666666666667]
 [0 0.666666666666667 4.83333333333333]] 

Step3: -Row2 * [0.0909090909090909] + Row 3 

[[6.00000000000000 2.00000000000000 1.00000000000000]
 [0 7.33333333333333 2.66666666666667]
 [0 0 4.59090909090909]]


Matrix([
[6.0,              2.0,              1.0],
[  0, 7.33333333333333, 2.66666666666667],
[  0,                0, 4.59090909090909]])

In [38]:
matrixl = test.lDecompost(l1,l2,l3)
matrixl

Matrix([
[              1.0,                0.0, 0.0],
[0.333333333333333,                1.0, 0.0],
[0.166666666666667, 0.0909090909090909, 1.0]])

STEP 1: Determining the 1st Column of $[A]^{-1}$
using
$$ [L]\{d\}_1 = \{b\}_1$$

$$ [U]\{x\}_1 = \{d\}_1 $$

where $ \{b\}_n $ is the nth column of the identity matrix and  $ \{x\}_n $ is the nth column of the inverse matrix

In [39]:
matrixI = np.identity(3)
Matrix(matrixI)


Matrix([
[1.0, 0.0, 0.0],
[0.0, 1.0, 0.0],
[0.0, 0.0, 1.0]])

In [11]:
#Finding D1
matrixd1= linalg.solve(np.array(matrixl.tolist()).astype(np.float64), matrixI[: , 0])
Matrix(matrixd1)

Matrix([
[               1.0],
[-0.333333333333333],
[-0.136363636363636]])

In [12]:
# FIrst Column
Imatrix1= linalg.solve(np.array(matrixu.tolist()).astype(np.float64), matrixd1)
Matrix(Imatrix1)

Matrix([
[  0.183168316831683],
[-0.0346534653465346],
[-0.0297029702970297]])

Repeat for the rest of the columns

In [13]:
#Finding D2
matrixd2= linalg.solve(np.array(matrixl.tolist()).astype(np.float64), matrixI[: , 1])
Matrix(matrixd2)

Matrix([
[                0.0],
[                1.0],
[-0.0909090909090909]])

In [14]:
# Second Column
Imatrix2= linalg.solve(np.array(matrixu.tolist()).astype(np.float64), matrixd2)
Matrix(Imatrix2)

Matrix([
[-0.0445544554455445],
[  0.143564356435644],
[-0.0198019801980198]])

In [15]:
#Finding D3
matrixd3= linalg.solve(np.array(matrixl.tolist()).astype(np.float64), matrixI[: , 2])
Matrix(matrixd3)

Matrix([
[0.0],
[0.0],
[1.0]])

In [16]:
# Third Column
Imatrix3= linalg.solve(np.array(matrixu.tolist()).astype(np.float64), matrixd3)
Matrix(Imatrix3)

Matrix([
[-0.0099009900990099],
[-0.0792079207920792],
[  0.217821782178218]])

In [17]:
InverseMatrix = np.array((Imatrix1,Imatrix2,Imatrix3))
Matrix(np.transpose(InverseMatrix))

Matrix([
[  0.183168316831683, -0.0445544554455445, -0.0099009900990099],
[-0.0346534653465346,   0.143564356435644, -0.0792079207920792],
[-0.0297029702970297, -0.0198019801980198,   0.217821782178218]])

Sanity Check to ensure is correct

In [18]:
Matrix(linalg.inv(test.matrixa.astype(np.float64)))

Matrix([
[  0.183168316831683, -0.0445544554455446, -0.0099009900990099],
[-0.0346534653465347,   0.143564356435644, -0.0792079207920792],
[-0.0297029702970297, -0.0198019801980198,   0.217821782178218]])

In [19]:
np.array(test.matrixA)[1][1]

8.00000000000000