In [8]:
import numpy as np
import scipy 
import pprint
from scipy import linalg
from sympy import *
import Matrix as CLO2



In [9]:
coeffequation1 = [2,1,1, 3]
coeffequation2 = [1,-1,-1,24 ]
coeffequation3 = [1,2,1, 123]

np.set_printoptions(precision=3)

test = CLO2.matrix(coeffequation1,coeffequation2,coeffequation3)
print(test.matrixa)


[[2 1 1]
 [1 -1 -1]
 [1 2 1]]


Using Matrix Decomposition to calculate Roots

TypeError: 'Integer' object is not subscriptable

In [10]:
matrixu, l1,l2,l3 = test.uDecompost(test.matrixa)
matrixu

U DECOMPOSITION
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Step 1: -Row1 * 1/2 + Row2
Step 2: -Row1 * 1/2 + Row2 yielding: 

[[2 1 1]
 [0 -3/2 -3/2]
 [0 3/2 1/2]] 

Step3: -Row2 * -1 + Row 3 

[[2 1 1]
 [0 -3/2 -3/2]
 [0 0 -1]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Matrix([
[2,    1,    1],
[0, -3/2, -3/2],
[0,    0,   -1]])

In [11]:
matrixl = test.lDecompost(l1,l2,l3)
matrixl

Matrix([
[1.0,  0.0, 0.0],
[0.5,  1.0, 0.0],
[0.5, -1.0, 1.0]])

In [12]:
matrixd = linalg.solve(np.array(matrixl.tolist()).astype(np.float64), test.matrixb)
matrixD = Matrix(matrixd)
matrixD

Matrix([
[  3.0],
[ 22.5],
[144.0]])

In [13]:
ans= linalg.solve(np.array(matrixu.tolist()).astype(np.float64), matrixd)
Matrix(ans)

Matrix([
[   9.0],
[ 129.0],
[-144.0]])

In [14]:
x1,x2 ,x3 = symbols('x1, x2, x3')
linsolve(Matrix(test.matrixdata), (x1,x2,x3))

FiniteSet((9, 129, -144))

$ \textbf{Using LU Decomposition to determine Inverse} $

using the principle of LU Decomposition
 $$ [A]^{-1} = \left[\{x\}_1 \{x\}_2 \{x\}_3 \right]$$
 
 where $ \{x\}_n $ represents the nth column of $[A]^{-1}$

In [15]:
test.matrixA

Matrix([
[2,  1,  1],
[1, -1, -1],
[1,  2,  1]])

In [18]:
matrixu, l1,l2,l3 = test.uDecompost(test.matrixa)
matrixu

U DECOMPOSITION
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Step 1: -Row1 * 1/2 + Row2
Step 2: -Row1 * 1/2 + Row2 yielding: 

[[2 1 1]
 [0 -3/2 -3/2]
 [0 3/2 1/2]] 

Step3: -Row2 * -1 + Row 3 

[[2 1 1]
 [0 -3/2 -3/2]
 [0 0 -1]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Matrix([
[2,    1,    1],
[0, -3/2, -3/2],
[0,    0,   -1]])

In [19]:
matrixl = test.lDecompost(l1,l2,l3)
matrixl

Matrix([
[1.0,  0.0, 0.0],
[0.5,  1.0, 0.0],
[0.5, -1.0, 1.0]])

STEP 1: Determining the 1st Column of $[A]^{-1}$
using
$$ [L]\{d\}_1 = \{b\}_1$$

$$ [U]\{x\}_1 = \{d\}_1 $$

where $ \{b\}_n $ is the nth column of the identity matrix and  $ \{x\}_n $ is the nth column of the inverse matrix

In [20]:
matrixI = np.identity(3)
Matrix(matrixI)


Matrix([
[1.0, 0.0, 0.0],
[0.0, 1.0, 0.0],
[0.0, 0.0, 1.0]])

In [21]:
#Finding D1
matrixd1= linalg.solve(np.array(matrixl.tolist()).astype(np.float64), matrixI[: , 0])
Matrix(matrixd1)

Matrix([
[ 1.0],
[-0.5],
[-1.0]])

In [22]:
# FIrst Column
Imatrix1= linalg.solve(np.array(matrixu.tolist()).astype(np.float64), matrixd1)
Matrix(Imatrix1)

Matrix([
[ 0.333333333333333],
[-0.666666666666667],
[               1.0]])

Repeat for the rest of the columns

In [23]:
#Finding D2
matrixd2= linalg.solve(np.array(matrixl.tolist()).astype(np.float64), matrixI[: , 1])
Matrix(matrixd2)

Matrix([
[0.0],
[1.0],
[1.0]])

In [24]:
# Second Column
Imatrix2= linalg.solve(np.array(matrixu.tolist()).astype(np.float64), matrixd2)
Matrix(Imatrix2)

Matrix([
[0.333333333333333],
[0.333333333333333],
[             -1.0]])

In [25]:
#Finding D3
matrixd3= linalg.solve(np.array(matrixl.tolist()).astype(np.float64), matrixI[: , 2])
Matrix(matrixd3)

Matrix([
[0.0],
[0.0],
[1.0]])

In [26]:
# Third Column
Imatrix3= linalg.solve(np.array(matrixu.tolist()).astype(np.float64), matrixd3)
Matrix(Imatrix3)

Matrix([
[ 0.0],
[ 1.0],
[-1.0]])

In [27]:
InverseMatrix = np.array((Imatrix1,Imatrix2,Imatrix3))
Matrix(np.transpose(InverseMatrix))

Matrix([
[ 0.333333333333333, 0.333333333333333,  0.0],
[-0.666666666666667, 0.333333333333333,  1.0],
[               1.0,              -1.0, -1.0]])

Sanity Check to ensure is correct

In [28]:
Matrix(linalg.inv(test.matrixa.astype(np.float64)))

Matrix([
[ 0.333333333333333, 0.333333333333333,  0.0],
[-0.666666666666667, 0.333333333333333,  1.0],
[               1.0,              -1.0, -1.0]])